name: Publish

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install NPM dependencies
        run: npm install

      - name: Run Gulp tasks
        run: npx gulp

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore .NET dependencies
        run: dotnet restore

      - name: Set version variables
        id: vars
        run: |
          YEAR=$(date +'%Y')
          MONTH=$(date +'%m')
          DAY=$(date +'%d')
          VERSION_TAG="${YEAR}.${MONTH}.${DAY}.${{ github.run_number }}"
          echo "version_tag=$VERSION_TAG" >> $GITHUB_OUTPUT

      - name: Build .NET app
        run: dotnet build --configuration Release -p:Version=${{ steps.vars.outputs.version_tag }}

      - name: Publish .NET app
        run: dotnet publish --configuration Release --output ./publish

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.version_tag }}
